#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"

title: RKNFXX's mechanical machinations
description: Adventures in the world of mechanical keyboards, and other nonsense.
show_downloads: false

pages:
  - Home: index.md
  - Boards:
    - MasterKeys Pro S: boards/masterkeyspros.md

plugins:
  - jekyll-remote-theme
